require("core.functions")
require("core.options")
require("core.keymaps")
require("core.linting")

require("plugins.lazynvim")
require("plugins.treesitter")
require("plugins.nvimtree")
require("plugins.fzflua")
require("plugins.spectre")
require("plugins.aerial")
require("plugins.gitsigns")
require("plugins.autocomplete")
require("plugins.nvimnotify")
require("plugins.colorscheme")
