require('core.functions')
require('core.options')
require('core.keymaps')

require('plugins.lazynvim')
require('plugins.nvimtree')
-- require('plugins.telescope')
require('plugins.fzflua')
require('plugins.spectre')
require('plugins.aerial')
require('plugins.gitsigns')
require('plugins.masonlsp')
require('plugins.autocomplete')
require('plugins.formatting')
require('plugins.nvimnotify')
require('plugins.colorscheme')
