require("core.functions")
require("core.options")
require("core.keymaps")
require("core.ctags")
require("core.linting")
require("core.glean")

require("plugins.lazynvim")
require("plugins.treesitter")
require("plugins.nvimtree")
require("plugins.fzflua")
require("plugins.spectre")
require("plugins.aerial")
require("plugins.gitsigns")
require("plugins.autocomplete")
require("plugins.nvimnotify")
require("plugins.lualine")

-- Colorscheme must be the last one.
require("plugins.colorscheme")
